version: '3'

services:
  phoenix:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_dev
      POSTGRES_PORT: 54321
      POSTGRES_HOST: host.docker.internal 
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - 54321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: