version: '3'

services:
  phoenix:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_dev
      POSTGRES_PORT: 5432
      POSTGRES_HOST: demo_db_1
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: