version: '3'

services:
  phoenix:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sites_dev
      POSTGRES_PORT: 54322
      POSTGRES_HOST: host.docker.internal
      ERL_AFLAGS: -kernel shell_history enabled
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:10-2.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - 54322:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
