apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgres
resources:
- pvc.yaml
- deployment.yaml

secretGenerator:
  - name: postgres-env
    envs:
      - postgres.env

# configMapGenerator:
#   - name: postgres-config
#     files:
#       - config/initdb.sql