# what do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# how to implement it
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-pv
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube/local-storage"
    type: DirectoryOrCreate