apiVersion: v1
kind: Service
metadata:
  name: sites
  labels:
    app: sites
spec:
  ports:
    - port: 4000
      nodePort: 30000
  selector:
    app: sites
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sites-db
  labels:
    app: sites-db
spec:
  ports:
    - port: 5432
      nodePort: 30001
  selector:
    app: postgres
  type: NodePort
