---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sites
  namespace: default
  labels:
    app: sites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sites
  template:
    metadata:
      labels:
        app: sites
    spec:
      containers:
      - name: sites
        image: sites-liveview
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                name: sites-app-config
        ports:
        - containerPort: 4000
