name:  Build and Release Develop Branch

# on:
#   push

env:
  MIX_ENV: prod

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      
      - name: Pull Latest Code
        uses: actions/checkout@v2

      # --------------------- 
      # Env Setup
      # ---------------------
      - name: Get Vars
        uses: FranzDiebold/github-env-vars-action@v2

      # Examples for semver releases
      # https://github.com/jossef/action-semantic-release-info
      # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
      - name: Gets semantic release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # --------------------- 
      # ECR Build Release and Push Image
      # ---------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sites-liveview-releases
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c 1-7)
          IMAGE_TAG=$CI_REF_NAME-$COMMIT_HASH
          FULL_IMG_PATH=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # add image path to action env for migrations access
          echo "FULL_IMG_PATH=$FULL_IMG_PATH" >> $GITHUB_ENV

          docker build -f release.Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-env name=REPOSITORY_URI:$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
      # - name: Check semver stuff
      #   run: |
      #     echo release tag - ${{ steps.semantic_release_info.outputs.git_tag }}


      # --------------------- 
      # Push ECR Image to ECS Container
      # ---------------------
      # Updates the task def with the current semver
      # - name: Update task definition
      #   uses: jossef/action-set-json-field@v1
      #   with:
      #     file: task-definition.json
      #     field: version
      #     value: ${{ steps.semantic_release_info.outputs.git_tag }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition-develop.json
          container-name: sites-container-develop
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: sites-develop-service
          cluster: sites-2
          # wait-for-service-stability: true
